# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
env:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: builds project
        run: mvn compile
        
  test:
    name: test
    runs-on: self-hosted
    needs: build
    steps:
      - name: test project
        run: mvn test

  package:
    name: package
    runs-on: self-hosted
    needs: test
    steps:
      - name: create war file
        run: mvn package
      - uses: actions/upload-artifacts@v2
        with:
          name: game.war
          path: "target/*.war"
  
  deploy_test:
    name: deploy_test
    runs-on: self-hosted
    needs: package
    steps:
      - name: deploy
        run: cp -f ./target/*.war /usr/local/tomcat/webapps
  
